# SPDX-FileCopyrightText: 2020 Jeremy Lainé <jeremy.laine@m4x.org>
#
# SPDX-License-Identifier: CC0-1.0

name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      CONFIG: ${{ matrix.config }}
      QT_VERSION: ${{ matrix.qt_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        config: [minimal, full]
        qt_version: ['5.14.*']
        include:
          - os: ubuntu-latest
            config: full
            qt_version: 5.14.*
          - os: ubuntu-latest
            config: minimal
            qt_version: 5.14.*
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          setup-python: false
      - name: Install extra packages
        run: tests/travis/install-build-depends
      - name: Disable OS X firewall
        if: matrix.os == 'macos-latest'
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
      - name: Run tests
        run: tests/travis/build-and-test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  xmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install -y libxml2-utils
      - run: xmllint --noout $(find . -type f -name *.xml)
  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 15
          files-changed-only: false
          thread-comments: true
      - name: C++ Linter
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
