# SPDX-FileCopyrightText: 2020 Jeremy Lainé <jeremy.laine@m4x.org>
#
# SPDX-License-Identifier: CC0-1.0

name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      CONFIG: ${{ matrix.config }}
      QT_VERSION: ${{ matrix.qt_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        config: [minimal, full, full-debug]
        qt_version: ['5.15.*']
        include:
          - os: ubuntu-latest
            config: full
            qt_version: 5.9.*
          - os: ubuntu-latest
            config: minimal
            qt_version: 6.0.*
          - os: ubuntu-latest
            config: minimal
            qt_version: 6.*.*
          - os: macos-latest
            config: minimal
            qt_version: 6.*.*
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          setup-python: false
      - name: Install extra packages
        run: tests/travis/install-build-depends
      - name: Disable OS X firewall
        if: matrix.os == 'macos-latest'
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
      - name: Run tests
        run: tests/travis/build-and-test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Run tests
        run: |
          ${env:PATH} += ";D:/a/qxmpp/qxmpp/src/Debug"
          cmake . && cmake --build .
          # ctest
          # ctest --rerun-failed --output-on-failure
  xmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install -y libxml2-utils
      - run: xmllint --noout $(find . -type f -name *.xml)
  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
