# SPDX-FileCopyrightText: 2020 Jeremy Lainé <jeremy.laine@m4x.org>
#
# SPDX-License-Identifier: CC0-1.0

name: tests

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: debian:stable
    env:
      CONFIG: ${{ matrix.config }}
      QT_VERSION: ${{ matrix.qt_version }}
    strategy:
      fail-fast: false
      matrix:
<<<<<<< HEAD
        config: [minimal, full, full-debug]
        qt_version: ['5.15.*']
        include:
          - config: minimal
            qt_version: 6.1.*
          - config: full-debug
            qt_version: 6.5.3
    steps:
      - name: Install sudo
        run: apt update && apt install -qq -y sudo
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          modules: ${{ (startsWith(matrix.qt_version, '6.') && 'qt5compat') || '' }}
          setup-python: true
      - name: Install extra packages
        run: tests/travis/install-build-depends-debian
      - name: Run tests
        run: tests/travis/build-and-test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  macos:
    runs-on: macos-latest
    env:
      CONFIG: ${{ matrix.config }}
      QT_VERSION: ${{ matrix.qt_version }}
    strategy:
      fail-fast: false
      matrix:
        config: [minimal, full, full-debug]
        qt_version: ['5.15.*']
        include:
          - config: full-debug
            qt_version: 6.*.*
=======
        os: [ubuntu-latest]
        config: [minimal]
        qt_version: ['5.9.*']
        include:
          - os: ubuntu-latest
            config: minimal
            qt_version: 5.9.*
>>>>>>> 1.6
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          modules: ${{ matrix.qt_version[0] == '6' && 'qt5compat' || '' }}
      - name: Install extra packages
        run: tests/travis/install-build-depends-macos
      - name: Disable OS X firewall
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
      - name: Run tests
        run: tests/travis/build-and-test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
<<<<<<< HEAD

  windows:
    runs-on: windows-latest
    env:
      QT_VERSION: ${{ matrix.qt_version }}
    strategy:
      fail-fast: false
      matrix:
        qt_version: ['5.15.*', '6.*.*']
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
      - name: Run tests
        run: |
          ${env:PATH} += ";D:/a/qxmpp/qxmpp/src/Debug"
          cmake . && cmake --build .
          # ctest
          # ctest --rerun-failed --output-on-failure

  doxygen:
    runs-on: ubuntu-latest
    container:
      image: debian:stable
    steps:
      - name: Install dependencies
        run: apt update && apt install -qq -y sudo git clang cmake qt6-base-dev doxygen graphviz
      - uses: actions/checkout@v3
      - name: Build doxygen documentation
        run: tests/travis/build-documentation

=======
>>>>>>> 1.6
  xmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install -y libxml2-utils
      - run: xmllint --noout $(find . -type f -name *.xml)

  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
<<<<<<< HEAD

=======
>>>>>>> 1.6
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 15
          files-changed-only: false
<<<<<<< HEAD
          step-summary: true
          thread-comments: false
=======
          thread-comments: true
>>>>>>> 1.6
      - name: C++ Linter
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
